use_frameworks!

platform :ios, '9.0'

target 'ZZMediaClipper_Example' do
  pod 'ZZMediaClipper', :path => '../ZZMediaClipper'

  target 'ZZMediaClipper_Tests' do
    inherit! :search_paths

    
  end
end
